// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16YfXn_KFhCV_GlT0lifW19lAjQBb_9g',
    appId: '1:495594370579:web:195159f708af47fb1ab1e6',
    messagingSenderId: '495594370579',
    projectId: 'mockhangapp',
    authDomain: 'mockhangapp.firebaseapp.com',
    storageBucket: 'mockhangapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dI6k8r1Jjp3vxYKyH2XfIYb20sZJJs4',
    appId: '1:495594370579:android:c098dbda3c20e66b1ab1e6',
    messagingSenderId: '495594370579',
    projectId: 'mockhangapp',
    storageBucket: 'mockhangapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuFlngIVgiOOufFVLxDBU1KYSc2hSVIE',
    appId: '1:495594370579:ios:28734e06b43a5d0f1ab1e6',
    messagingSenderId: '495594370579',
    projectId: 'mockhangapp',
    storageBucket: 'mockhangapp.firebasestorage.app',
    iosClientId: '495594370579-g9nq4cj5o77lp9t67e4l72nmi5ce7lfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockhangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQuFlngIVgiOOufFVLxDBU1KYSc2hSVIE',
    appId: '1:495594370579:ios:28734e06b43a5d0f1ab1e6',
    messagingSenderId: '495594370579',
    projectId: 'mockhangapp',
    storageBucket: 'mockhangapp.firebasestorage.app',
    iosClientId: '495594370579-g9nq4cj5o77lp9t67e4l72nmi5ce7lfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockhangApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16YfXn_KFhCV_GlT0lifW19lAjQBb_9g',
    appId: '1:495594370579:web:c0b23e090fe5c5b31ab1e6',
    messagingSenderId: '495594370579',
    projectId: 'mockhangapp',
    authDomain: 'mockhangapp.firebaseapp.com',
    storageBucket: 'mockhangapp.firebasestorage.app',
  );

}